Repository Dae-Hwa/todo-list, pull requests merged in 2021-04, with the labels that each got.

#11 [InitView]개선-
  README.md
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/xcuserdata/jinseopark.xcuserdatad/UserInterfaceState.xcuserstate
  Todo_List/Todo_List.xcodeproj/xcuserdata/jinseopark.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Todo_List/Todo_List/Controller/TaskViewController.swift
  Todo_List/Todo_List/StoryBoard/Base.lproj/Main.storyboard
  Todo_List/Todo_List/View/TaskCell.swift
  Todo_List/Todo_List/View/TaskCell.xib
Labels: IOS

#14 [iOS] plus 버튼 기능 추가
  Todo_List/Todo_List.xcodeproj/project.pbxproj
  Todo_List/Todo_List/Controller/TaskViewController.swift
  Todo_List/Todo_List/Model/TaskVO.swift
  Todo_List/Todo_List/StoryBoard/Base.lproj/Main.storyboard
  Todo_List/Todo_List/View/TaskCell.swift
  Todo_List/Todo_List/View/TaskCell.xib
Labels: IOS

#13 Mockup api 생성
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/Task.java
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/TaskController.java
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/TaskRepository.java
  backend/todo-list-backend/src/main/resources/application.properties
Labels: BE

#16 [iOS] 추가 모달 뷰 생성 및 main화면에 반영
  README.md
  Todo_List/Todo_List.xcodeproj/project.pbxproj
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/xcuserdata/jinseopark.xcuserdatad/UserInterfaceState.xcuserstate
  Todo_List/Todo_List.xcodeproj/xcuserdata/jinseopark.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Todo_List/Todo_List/Assets.xcassets/add.imageset/Contents.json
  Todo_List/Todo_List/Assets.xcassets/add.imageset/add.png
  Todo_List/Todo_List/Assets.xcassets/add_highlight.imageset/Contents.json
  Todo_List/Todo_List/Assets.xcassets/add_highlight.imageset/add_highlight.png
  Todo_List/Todo_List/Controller/AddPopUpViewController.swift
  Todo_List/Todo_List/Controller/ModalViewController.swift
  Todo_List/Todo_List/Controller/TaskViewController.swift
  Todo_List/Todo_List/Model/TaskVO.swift
  Todo_List/Todo_List/Model/TaskVOManager.swift
  Todo_List/Todo_List/StoryBoard/Base.lproj/Main.storyboard
  Todo_List/Todo_List/StoryBoard/Modal.storyboard
  Todo_List/Todo_List/View/TaskCell.swift
  Todo_List/Todo_List/View/TaskCell.xib
Labels: IOS

#21 [iOS] Notification추가 및 추가 버튼 IBOutlet Collection 적용
  Todo_List/Todo_List/Controller/CardViewController.swift
  Todo_List/Todo_List/Model/Board.swift
  Todo_List/Todo_List/StoryBoard/Base.lproj/Main.storyboard
Labels: IOS

#25 [BE] delete시 previousId 참조 문제 해결
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/TaskController.java
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/TaskRepository.java
Labels: BE, bug

#26 [iOS] 네트워크 연결
  Todo_List/Todo_List.xcodeproj/project.pbxproj
  Todo_List/Todo_List/Assets.xcassets/Gray5.colorset/Contents.json
  Todo_List/Todo_List/Assets.xcassets/blue.colorset/Contents.json
  Todo_List/Todo_List/Assets.xcassets/lightBlue.colorset/Contents.json
  Todo_List/Todo_List/Controller/CardViewController+Data.swift
  Todo_List/Todo_List/Controller/CardViewController.swift
  Todo_List/Todo_List/Controller/ModalViewController.swift
  Todo_List/Todo_List/Model/Board.swift
  Todo_List/Todo_List/Model/Card.swift
  Todo_List/Todo_List/Model/Cards.swift
  Todo_List/Todo_List/Network/APIError.swift
  Todo_List/Todo_List/Network/CardAPI.swift
  Todo_List/Todo_List/Network/CardAPIClient.swift
  Todo_List/Todo_List/Network/CardsAPI.swift
  Todo_List/Todo_List/Network/HTTPMethod.swift
  Todo_List/Todo_List/Network/URLSessionProtocol.swift
  Todo_List/Todo_List/StoryBoard/Modal.storyboard
Labels: IOS

#29 Drag n Drop 기능 추가
  .DS_Store
  Todo_List/.DS_Store
  Todo_List/Todo_List.xcodeproj/project.pbxproj
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/xcuserdata/jinseopark.xcuserdatad/UserInterfaceState.xcuserstate
  Todo_List/Todo_List.xcodeproj/xcuserdata/jinseopark.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Todo_List/Todo_List/.DS_Store
  Todo_List/Todo_List/Controller/AddPopUpViewController.swift
  Todo_List/Todo_List/Controller/CardViewController+Data.swift
  Todo_List/Todo_List/Controller/CardViewController+Drag.swift
  Todo_List/Todo_List/Controller/CardViewController+Drop.swift
  Todo_List/Todo_List/Controller/CardViewController.swift
  Todo_List/Todo_List/Model/Board.swift
  Todo_List/Todo_List/Model/Card.swift
  Todo_List/Todo_List/Model/CardManager.swift
Labels: IOS

#33 [BE] tasktype 추가 및 인터페이스 수정
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/Task.java
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/TaskController.java
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/TaskDTO.java
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/TaskRepository.java
  backend/todo-list-backend/src/main/java/com/codesquad/esfj/todolist/task/TaskService.java
Labels: BE

#35 [iOS] 전반적인 구조 변경 및 네트워크 수정
  .DS_Store
  Todo_List/Todo_List.xcodeproj/project.pbxproj
  Todo_List/Todo_List.xcodeproj/project.xcworkspace/xcuserdata/jinseopark.xcuserdatad/UserInterfaceState.xcuserstate
  Todo_List/Todo_List.xcodeproj/xcuserdata/jinseopark.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Todo_List/Todo_List/Controller/CardViewController+Data.swift
  Todo_List/Todo_List/Controller/CardViewController+Drag.swift
  Todo_List/Todo_List/Controller/CardViewController+Drop.swift
  Todo_List/Todo_List/Controller/CardViewController.swift
  Todo_List/Todo_List/Controller/ModalViewController.swift
  Todo_List/Todo_List/Controller/ViewController.swift
  Todo_List/Todo_List/Delegate/TableViewDataSource.swift
  Todo_List/Todo_List/Delegate/TableViewDelegate.swift
  Todo_List/Todo_List/Delegate/TableViewDragDelegate.swift
  Todo_List/Todo_List/Delegate/TableViewDropDelegate.swift
  Todo_List/Todo_List/Model/Board.swift
  Todo_List/Todo_List/Model/Card.swift
  Todo_List/Todo_List/Model/CardManager.swift
  Todo_List/Todo_List/Model/CardType.swift
  Todo_List/Todo_List/Model/Cards.swift
  Todo_List/Todo_List/Network/CardAPIClient.swift
  Todo_List/Todo_List/Network/ClientError.swift
  Todo_List/Todo_List/Network/HTTPMethod.swift
  Todo_List/Todo_List/Network/NetworkResponse.swift
  Todo_List/Todo_List/StoryBoard/Base.lproj/Main.storyboard
  Todo_List/Todo_List/View/CardCell.swift
  Todo_List/Todo_List/View/CardViewConstant.swift
Labels: IOS
